[package]
name = "alkoholiq"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
brainfuck = "0.2.1"
pest = "2.7.15"
pest_derive = "2.7.15"
thiserror = "2.0.12"
#logos = { version = "0.15.0", features = [] }
