[package]
name = "alkoholiq"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
argh = { version = "0.1.13", default-features = false, features = ["help"] }
pest = "2.7.15"
pest_derive = "2.7.15"
thiserror = "2.0.12"
#logos = { version = "0.15.0", features = [] }
