pub mod optim;
mod interpreter;

pub fn add_header(s: String) -> String {
    let header = format!(
        "[Generated by alkoholiq v{}. See https://github.com/3top1a/alkoholiq]",
        env!("CARGO_PKG_VERSION")
    );
    format!("{}\n{}", header, s)
}
