pub mod interpreter;
pub mod optim;

pub fn add_header(s: String) -> String {
    let header = format!(
        "[Generated by alkoholiq v{}. See https://github.com/3top1a/alkoholiq]",
        env!("CARGO_PKG_VERSION")
    );
    format!("{header}\n{s}")
}

pub fn optimize(bf: String) -> String {
    let bf = optim::optimize_no_effect(bf);
    let bf = optim::remove_redundant_zeros(bf);
    let bf = optim::optimize_no_effect(bf);
    let bf = optim::remove_non_brainfuck(bf);
    add_header(bf)
}
